### ISSUE TITLE
please update to base64 0.11.0

### ISSUE THREAD

**Issue by hpk42** [hsivonen/charset#1]
and publish a new crate if possible. thanks :)

**Comment by hsivonen** [comment]
> and publish a new crate if possible.

How urgent is this for you?

It looks like the reason why `base64` did a semver-breaking version increment is that its minimum supported Rust version changed to 1.34. This crate's previous MSRV was 1.31. If _this_ crate doesn't now treat an MSRV change as requiring a semver change, `base64`'s semver change is pointless. However, it's bad for the ecosystem for one MSRV change at a leaf crate to cause a semver change and associated work for all transitively dependent crates when there are no breaking API or behavior changes.

The [RFC for resolving for this problem](https://github.com/rust-lang/rfcs/pull/2495) was finally merged in October. It this crate waited for [implementation](https://github.com/rust-lang/rust/issues/65262) to arrive before doing a new release, the next release of this crate could specify MSRV in `Cargo.toml` without a semver change.

**Comment by hpk42** [comment]
On Mon, Jan 13, 2020 at 09:32 -0800, Henri Sivonen wrote:
> > and publish a new crate if possible.
> 
> How urgent is this for you?

it's not very urgent but leads to duplicate dependencies. 

> It looks like the reason why `base64` did a semver-breaking version increment is that its minimum supported Rust version changed to 1.34. This crate's previous MSRV was 1.31. If _this_ crate doesn't now treat an MSRV change as requiring a semver change, `base64`'s semver change is pointless. However, it's bad for the ecosystem for one MSRV change at a leaf crate to cause a semver change and associated work for all transitively dependent crates when there are no breaking API or behavior changes.

indeed. 

thanks for caring.
