### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by dignifiedquire** [hsivonen/charset#3]
Could you create a new release please, with the updated dependencies? thank you

**Comment by link2xt** [comment]
cc @hsivonen

**Comment by link2xt** [comment]
There is a PR #4 open for it.

**Comment by hsivonen** [comment]
I have pushed a new release after coming to the conclusion that it doesn't make sense to do semver bumps of this crate for the semver bumps of `base64`. Sorry about taking so long.
